version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: game
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:secret@postgres:5432/game?sslmode=disable"
    ports:
      - "3000:3000"
